name: Installing Python
'on':
  - push
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.4 
          - macos-14
          - windows-latest
        py-version:
          - "3.10"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.py-version }}'
